meta_product_name: "Question Hero"
meta_title: "Question Hero - Instant help for your school questions"
meta_description: "Question Hero connects eager learners with tutors - fast. Get your most frustrating questions answered quickly and affordably now."
meta_image: "students.jpg" # should exist in `app/assets/images/`
